import footerObjects from "../objects/footerObjects.cy";

const footer = new footerObjects()

describe('Macdosoft Footer Section', () =>{
    it('Footer Section Visit', () =>{

        cy.visit('https://macdosoft.com/')
        cy.wait(1000)


        footer.clickCustomSoftwareSolutions()
        footer.clickHome()
        footer.clickWebDevelopment()
        footer.clickHome()
        footer.clickSoftwareTestingQA()
        footer.clickHome()
        footer.clickMachineLearningSolutions()
        footer.clickHome()
        footer.clickAIChatbots()
        footer.clickHome()
        footer.clickPredictiveAnalytics()
        footer.clickHome()
        footer.clickFrontendBackendDevelopment()
        footer.clickHome()
        footer.clickFullStackCMSSolutions()
        footer.clickHome()
        footer.clickEcommerceDevelopment()
        footer.clickHome()
        footer.clickProgressiveWebApps()
        footer.clickHome()
        footer.clickUIUX()
        footer.clickHome()
        footer.clickWireframingPrototyping()
        footer.clickHome()
        footer.clickUserTestingFeedback()
        footer.clickHome()
        footer.clickDesignSystems()
        footer.clickHome()
        footer.clickSoftwareConsulting()
        footer.clickHome()
        footer.clickTechnologyConsulting()
        footer.clickHome()
        footer.clickSystemIntegration()
        footer.clickHome()
        footer.clickProjectManagement()
        footer.clickHome()
        footer.clickCustomCRMSolutions()
        footer.clickHome()
        footer.clickCRMIntegration()
        footer.clickHome()
        footer.clickCRMSystemCustomization()
        footer.clickHome()
        footer.clickiOSAndroidDevelopment()
        footer.clickHome()
        footer.clickCrossPlatform()
        footer.clickHome()
        footer.clickAppDesignPrototyping()
        footer.clickHome()
        footer.clickiOSAndroidDevelopment()
        footer.clickHome()
        footer.clickCrossPlatform()
        footer.clickHome()
        footer.clickAppDesignPrototyping()
        footer.clickHome()
        footer.clickCloudArchitectureDesign()
        footer.clickHome()
        footer.clickCloudAppIntegration()
        footer.clickHome()
        footer.clickCloudMigrationServices()
        footer.clickHome()
        footer.clickMicroservicesArchitecture()
        footer.clickHome()
        footer.clickCICDPipelineImplementation()
        footer.clickHome()
        footer.clickInfrastructureCode()
        footer.clickHome()
        footer.clickContainerization()
        footer.clickHome()
        footer.clickCloudAutomation()
        footer.clickHome()
        footer.click247Support()
        footer.clickHome()
        footer.clickOngoingMaintenance()
        footer.clickHome()
        footer.clickPerformanceMonitoring()
        footer.clickHome()
        // footer.
        // footer.clickHome()



        // footer.
        // footer.clickHome()

        
    })

})